# Generated by Django 5.0.6 on 2026-06-04 15:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_required_machine_type(apps, schema_editor):
    MachineRequest = apps.get_model('core', 'MachineRequest')
    MachineRequest.objects.filter(requested_item_type='', required_machine_type__gt='').update(
        requested_item_type=models.F('required_machine_type')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_optional_name_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='request_category',
            field=models.CharField(choices=[('equipment', 'Construction Equipment'), ('material', 'Construction Material')], default='equipment', max_length=24),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='requested_item_type',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='required_machine_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.RunPython(copy_required_machine_type, migrations.RunPython.noop),
    ]
